name: qiblah_pro
description: "Prayer times app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.4
  mask_text_input_formatter: ^2.9.0
  flutter_telegram_login: ^0.0.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  dio: ^5.4.0
  adaptive_theme: ^3.6.0
  equatable: ^2.0.5
  image_picker: ^1.0.7
  flutter_dash: ^1.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_share: ^2.0.0
  google_fonts: ^4.0.4
  flutter_svg_image: ^1.1.0+1
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  draggable_scrollbar: ^0.1.0
  dartz: ^0.10.1
  geocoding: ^2.1.1
  adhan: ^2.0.0+1
  pie_chart: ^5.4.0
  hijri: ^3.0.0
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  just_audio: ^0.9.36
  fl_country_code_picker: ^0.1.9+1
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^1.0.0
  flutter_timezone: ^1.0.8
  vector_math: ^2.1.4
  flutter_compass: ^0.8.0
  vibration: ^1.8.4
  permission_handler: ^11.3.0
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  uuid: ^4.3.3
  html_unescape: ^2.0.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.10.2
  webview_flutter: ^4.7.0



dev_dependencies:
  build_runner:
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.10
  flutter_svg_provider: ^1.0.4
  audio_session: ^0.1.18

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/icons/appLogo.svg



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/html/
    - lib/core/lang/
    - assets/music/
    - assets/jsons/
    - assets/images/images/


 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
