name: qiblah_pro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.3
  mask_text_input_formatter: ^2.8.0
  url_launcher: ^6.2.3
  flutter_telegram_login: ^0.0.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^6.0.4
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.7
  dio: ^5.4.0
  adaptive_theme: ^3.5.0
  equatable: ^2.0.5
  permission_handler: ^11.2.0
  location: ^5.0.3
  image_picker: ^1.0.7
  flutter_dash: ^1.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_share: ^2.0.0
  google_fonts: ^4.0.4
  flutter_svg_image: ^1.1.0+1
  intl: ^0.18.1
  webview_flutter: ^4.4.4
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  draggable_scrollbar: ^0.1.0
  dartz: ^0.10.1
  country_state_city_pro: ^0.0.6
  geocoding: ^2.1.1
  adhan: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/html/
    - lib/core/lang/

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
